### ISSUE TITLE
ArgumentException on line 94 Program.cs

### ISSUE THREAD

**Issue by SihleGatsheni** [KingGatsheni/CoffeeShop#2]
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 2
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)

**Comment by SihleGatsheni** [comment]
Fixed
